name: sessionrecord
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  riverpod: ^1.0.3
  shared_preferences: ^2.0.13
  flutter_screenutil: ^5.3.1
  firebase_core: ^1.14.0
  cloud_firestore: ^3.1.11
  image_picker: ^0.8.5
  firebase_storage: ^10.2.11
  flutter_riverpod: ^1.0.3
  awesome_dialog: ^2.2.0
  crypto: ^3.0.1
  url_launcher: ^6.1.2
  awesome_notifications: ^0.6.21
  flutter_background: ^1.1.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
