// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArhwY0PEL0pRcw8yESmZwBAWiBzqVQ1WE',
    appId: '1:913243441863:web:08f85811c42596678f4ce2',
    messagingSenderId: '913243441863',
    projectId: 'sessionrecord-9c9ea',
    authDomain: 'sessionrecord-9c9ea.firebaseapp.com',
    databaseURL: 'https://sessionrecord-9c9ea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sessionrecord-9c9ea.appspot.com',
    measurementId: 'G-JKBQF42DNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_7jyW7dIxV1bhWRKpIq9gQm3UMoRifek',
    appId: '1:913243441863:android:b1af85fcf9fea4108f4ce2',
    messagingSenderId: '913243441863',
    projectId: 'sessionrecord-9c9ea',
    databaseURL: 'https://sessionrecord-9c9ea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sessionrecord-9c9ea.appspot.com',
  );
}
